---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  labels:
    app: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      # hostNetwork: true
      containers:
      - name:  test
        image: docker-hub.bdp.pro:5000/sqlapi_base:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm # cmName
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  secret-mysql
              key:  MYSQL_PASSWD
        - name: MYSQL_DATABASE
          value: 'datacenter'
      restartPolicy: Always 

---
apiVersion: v1
kind: Service
metadata:
  name: app-test-svc2
spec:
  type: NodePort
  selector:
    app: app-test
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30003
