apiVersion: v1
kind: Pod
metadata:
  name: ${podName}
spec:
  volumes:
    - name: bdp-lib
      hostPath:
        path: /data/data/edm/lib
    - name: repo-path
      hostPath:
        path: ${repoHostPath}
        type: DirectoryOrCreate
    - name: run-path
      hostPath:
        path: /data/data/edm/docker/config
        type: DirectoryOrCreate
    - name: run-share
      hostPath:
        path: /data/data/edm/data/share
        type: DirectoryOrCreate
    - name: data-private
      hostPath:
        path: /data/data/edm/data/data/private/${USERID}
        type: DirectoryOrCreate
    - name: data-shared
      hostPath:
        path: /data/data/edm/data/data/shared
        type: DirectoryOrCreate
    - name: data-sdg
      hostPath:
        path: /data/data/edm/data/data/sdg
        type: DirectoryOrCreate
    - name: data-image
      hostPath:
        path: /mnt/File_Storage01/BDP/data/data_image
        type: DirectoryOrCreate
    - name: bdp-tmp
      hostPath:
        path: /data/data/edm/data/temp/
        type: DirectoryOrCreate
    - name: cluster-share-storage01
      hostPath:
        path: /opt/data/Cluster_Share_Storage01/
        type: DirectoryOrCreate
  containers:
  - name: ${podName}-${cName}
    image: ${imageName}
    imagePullPolicy: IfNotPresent
    command: [ 'sh' ] #启动容器的运行命令，将覆盖容器中的Entrypoint,对应Dockefile中的ENTRYPOINT
    args: [ "$(runner)" ] #启动容器的命令参数，对应Dockerfile中CMD参数
    tty: true
    env:
      - name: REPO_URL
        value: "${gitSSHURL}"
      - name: MAIN_FILE
        value: ".python.py"
      - name: USERID
        value: "${USERID}"
      - name: GITCOMMITID
        value: "${GITCOMMITID}"
      - name: USER_TOKEN
        value: "${user_token}"
      - name: runner #变量的名字
        value: "/run_path/run.sh" #变量的值
      - name: python_file
        value: ${file}
      - name: PYTHONPATH
        value: /bdp-lib:/project/libs
      - name: TZ
        value: Asia/Shanghai
    volumeMounts:
      - mountPath: /bdp-lib
        name: bdp-lib
        readOnly: true
      - mountPath: /project/
        name: repo-path
      - mountPath: /run_path/
        name: run-path
        readOnly: true
      - mountPath: /data/data/edm/data/share/
        name: run-share
      - mountPath: /Private/File/
        name: data-private
      - mountPath: /Public/File/
        name: data-shared
      - mountPath: /sdg/
        name: data-sdg
      - mountPath: /bdp-tmp
        name: bdp-tmp
      - mountPath: /data
        name: data-image
      - mountPath: /opt/data/Cluster_Share_Storage01/
        name: cluster-share-storage01
  nodeSelector:
    pyenv: ${pyenv}
  hostNetwork: true
  restartPolicy: Never
  serviceAccountName: spark
